#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cases="acoustic solid"

for case in $cases
do
    cd $case
    cleanCase $case
    cd ..
done

cd acoustic
\rm -f constant/solid system/solid 0/solid
cd ..

cd solid
\rm -f 0/0 constant/constant
cd ..
