#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application=acousticStructureInteractionFoam

cd acoustic
#runApplication blockMesh
cd constant
ln -s ../../solid/constant solid
cd ..
cd 0
ln -s ../../solid/0 solid
cd ..
cd ..

cd solid
runApplication blockMesh
cd ..
pwd

makeFsiCaseLinks acoustic solid
cd acoustic
runApplication $application
cd ..
makeFsiResultsLinks acoustic solid
